dependencies:
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- name: go-demo-6
  repository: http://jenkins-x-chartmuseum:8080
  version: 4.0.6
- name: jx-k8s-days-go-01
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
- name: jx-k8s-days-go-02
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
